### ISSUE TITLE
(Docker) Reverse proxy setup issue

### ISSUE THREAD

**Issue by jwillmer** [popeen/Booksonic-Air#23]
I get the following error if I use a reverse proxy (traefik2):

![image](https://user-images.githubusercontent.com/1503577/95969285-cb6a3b80-0e0e-11eb-8136-362139911dec.png)

```
---
version: "2.1"
services:
  booksonic-air:
    image: linuxserver/booksonic-air
    container_name: booksonic-air
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - </path/to/appdata/config>:/config
      - </path/to/audiobooks>:/audiobooks
      - </path/to/podcasts>:/podcasts
      - </path/to/othermedia>:/othermedia
    restart: unless-stopped
    labels:
      - "traefik.http.routers.audiobooks.rule=Host(`${AUDIOBOOKS_DOMAIN}`)"    
      - "traefik.http.routers.audiobooks.entrypoints=https"  
      - "traefik.http.routers.audiobooks.service=audiobooks"
      - "traefik.http.services.audiobooks.loadbalancer.server.port=4040"
```

Am I missing some configuration parts?
